# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20171225_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='SLUG DEFAULT'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='isPrimary',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
