# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20171228_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='SLUG DEFAULT', max_length=200),
        ),
    ]
